// Generated by Wrangler on Fri Dec 20 2024 15:36:19 GMT+0200 (Eastern European Standard Time)
// by running `wrangler types`

interface Env {
  WS_OBJECT: DurableObjectNamespace; /* WebSocketObject */
}
