name = "cf-automerge-overload"
main = "src/index.ts"
account_id = "950816f3f59b079880a1ae33fb0ec320"
compatibility_date = "2024-07-18"
compatibility_flags = ["nodejs_compat"]

[[migrations]]
	tag = "v1"
	new_classes = ["WebSocketObject"]

[[durable_objects.bindings]]
	name = "WS_OBJECT"
	class_name = "WebSocketObject"
